language: java

cache:
  directories:
    - fop-1.1

env:
  global:
    - DISPLAY=:99.0

sudo: false

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y xsltproc

script:
  - ./install-docbook-xsl.sh
   # Make sure stdout is in blocking mode.
   # See https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-348435959 for details.
  - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
  - ant -Dfop=fop-1.1/fop -Dout="$TRAVIS_BUILD_DIR/out"

deploy:
  - provider: script
    script: rsync -aP -e ssh --delete out/ bnl-jenkins,cs-studio@web.sourceforge.net:htdocs/docbook
    on:
      branch: master
